packaging_format = 2

id = "orthoptie"
name = "Dossiers Patients Orthoptie"
description.en = "Patient records management for orthoptic practice"
description.fr = "Gestion des dossiers patients pour cabinet d'orthoptie"

version = "1.0~ynh1"

maintainers = ["tanios43"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/tanios43/orthoptie_ynh"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "200M"
ram.build = "200M"
ram.runtime = "100M"

[install]

    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "admins"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/tanios43/orthoptie_ynh/archive/refs/tags/v1.1.tar.gz"
        sha256 = "d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed"
        format = "tar.gz"
        extract = true
        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]
    dir = "/var/www/__APP__"
    owner = "__APP__:rwx"
    group = "www-data:r-x"

    [resources.data_dir]
    dir = "/home/yunohost.app/__APP__"
    owner = "__APP__:rwx"

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]
    main.default = 5001

    [resources.apt]
    packages = "python3, python3-pip, python3-venv, libreoffice, poppler-utils"
