#!/bin/bash
source /usr/share/yunohost/helpers

ynh_script_progression --message="Sauvegarde des fichiers de l'application..." --weight=1
ynh_backup --src_path="$install_dir"

ynh_script_progression --message="Sauvegarde des données..." --weight=2
ynh_backup --src_path="$data_dir"

ynh_script_progression --message="Sauvegarde de la configuration nginx..." --weight=1
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_script_progression --message="Sauvegarde terminée !" --last
